import { Agent } from '../types/agent';

export const replitAgents: Agent[] = [
  {
    id: 'replit-ai-python-data-science',
    name: 'Python Data Science',
    description: 'The perfect starting place for data science. NumPy, Pandas, Matplotlib, Tensorflow, others are all installed.',
    fullDescription: 'A comprehensive Python environment pre-configured for data science. Includes essential libraries like NumPy, Pandas, Matplotlib, Scikit-learn, and TensorFlow, allowing you to start analyzing data and building models immediately without complex setup.',
    tool: 'replit',
    type: 'template',
    category: 'data',
    tags: ['AI', 'Data Science', 'Python', 'NumPy', 'Pandas'],
    author: {
      name: 'replit',
      url: 'https://replit.com/@replit',
    },
    installation: {
      type: 'other',
      instructions: 'Click "Use Template" on the Replit project page.',
      url: 'https://replit.com/@replit/Python-Data-Science',
    },
    verified: true,
    createdAt: '2025-12-06',
  },
  {
    id: 'replit-ai-openai-python-gpt4',
    name: 'OpenAI Python GPT-4',
    description: 'Access the OpenAI GPT-4 chat AI model using Python. Create your own LLM-driven AI server!',
    fullDescription: 'Starter code to interact with OpenAI\'s most capable model, GPT-4. Perfect for building chatbots, content generators, or any application requiring advanced natural language understanding.',
    tool: 'replit',
    type: 'template',
    category: 'coding',
    tags: ['AI', 'OpenAI', 'GPT-4', 'Python', 'LLM'],
    author: {
      name: 'replit',
      url: 'https://replit.com/@replit',
    },
    installation: {
      type: 'other',
      instructions: 'Click "Use Template" on the Replit project page.',
      url: 'https://replit.com/@replit/OpenAI-Python-GPT-4',
    },
    verified: true,
    createdAt: '2025-12-06',
  },
  {
    id: 'replit-ai-openai-python-gpt35',
    name: 'OpenAI Python GPT 3.5 Turbo',
    description: 'Access the OpenAI GPT-3.5 Turbo chat AI model using Python. Create your own LLM-driven AI server!',
    fullDescription: 'A cost-effective way to integrate OpenAI\'s chat models. Uses GPT-3.5 Turbo for fast, efficient, and capable AI interactions suitable for most chat applications.',
    tool: 'replit',
    type: 'template',
    category: 'coding',
    tags: ['AI', 'OpenAI', 'GPT-3.5', 'Python', 'Chatbot'],
    author: {
      name: 'replit',
      url: 'https://replit.com/@replit',
    },
    installation: {
      type: 'other',
      instructions: 'Click "Use Template" on the Replit project page.',
      url: 'https://replit.com/@replit/OpenAI-Python-GPT-35-Turbo',
    },
    verified: true,
    createdAt: '2025-12-06',
  },
  {
    id: 'replit-web-html-css-js-static',
    name: 'HTML, CSS, JS (Static)',
    description: 'The languages that make up the web. HTML provides structure, CSS controls formatting, and JavaScript controls behavior.',
    fullDescription: 'The fundamental building blocks of the web. This template sets up a standard structure for static websites with no build step required. Ideal for beginners learning web development or simple landing pages.',
    tool: 'replit',
    type: 'template',
    category: 'web',
    tags: ['Web', 'HTML', 'CSS', 'JavaScript', 'Static'],
    author: {
      name: 'replit',
      url: 'https://replit.com/@replit',
    },
    installation: {
      type: 'other',
      instructions: 'Click "Use Template" on the Replit project page.',
      url: 'https://replit.com/@replit/HTML-CSS-JS-Static',
    },
    verified: true,
    createdAt: '2025-12-06',
  },
  {
    id: 'replit-web-react-javascript',
    name: 'React Javascript',
    description: 'Online React Editor and IDE: compile, run, and host React apps.',
    fullDescription: 'A ready-to-go React environment powered by Vite. Experience fast refresh times and a modern build pipeline without configuring Webpack or Babel manually.',
    tool: 'replit',
    type: 'template',
    category: 'web',
    tags: ['Web', 'React', 'JavaScript', 'Vite', 'Frontend'],
    author: {
      name: 'replit',
      url: 'https://replit.com/@replit',
    },
    installation: {
      type: 'other',
      instructions: 'Click "Use Template" on the Replit project page.',
      url: 'https://replit.com/@replit/React-Javascript',
    },
    verified: true,
    createdAt: '2025-12-06',
  },
  {
    id: 'replit-web-html-css-js-vite',
    name: 'HTML, CSS, JS (Auto Refresh)',
    description: 'A starter for building a website with HTML, CSS and JS, powered by Vite.',
    fullDescription: 'Enhance your vanilla web development with Vite. This template gives you Hot Module Replacement (HMR) / Auto Refresh capabilities, making the development loop significantly faster than standard static file editing.',
    tool: 'replit',
    type: 'template',
    category: 'web',
    tags: ['Web', 'Vite', 'HTML', 'CSS', 'JavaScript'],
    author: {
      name: 'replit',
      url: 'https://replit.com/@replit',
    },
    installation: {
      type: 'other',
      instructions: 'Click "Use Template" on the Replit project page.',
      url: 'https://replit.com/@replit/HTML-CSS-JS-Auto-Refresh',
    },
    verified: true,
    createdAt: '2025-12-06',
  },
  {
    id: 'replit-gfx-python-turtle',
    name: 'Python (with Turtle)',
    description: 'Turtle is a pre-installed Python library that enables users to create pictures and shapes.',
    fullDescription: 'A classic educational tool. Control an on-screen "turtle" to draw shapes and patterns using simple Python commands. Excellent for visual learners and teaching programming logic.',
    tool: 'replit',
    type: 'template',
    category: 'coding',
    tags: ['Graphics', 'Python', 'Turtle', 'Education'],
    author: {
      name: 'replit',
      url: 'https://replit.com/@replit',
    },
    installation: {
      type: 'other',
      instructions: 'Click "Use Template" on the Replit project page.',
      url: 'https://replit.com/@replit/Python-with-Turtle',
    },
    verified: true,
    createdAt: '2025-12-06',
  },
  {
    id: 'replit-gfx-p5js',
    name: 'p5.js',
    description: 'JavaScript library for creative coding, accessible for artists, designers, educators, and beginners.',
    fullDescription: 'Create interactive art and visualizations in the browser. p5.js simplifes the process of drawing on the HTML5 canvas, making it easy to create animations, generative art, and interactive graphics.',
    tool: 'replit',
    type: 'template',
    category: 'coding',
    tags: ['Graphics', 'JavaScript', 'Creative Coding', 'p5.js'],
    author: {
      name: 'replit',
      url: 'https://replit.com/@replit',
    },
    installation: {
      type: 'other',
      instructions: 'Click "Use Template" on the Replit project page.',
      url: 'https://replit.com/@replit/p5js',
    },
    verified: true,
    createdAt: '2025-12-06',
  },
  {
    id: 'replit-gfx-tkinter',
    name: 'tkinter',
    description: 'Tkinter is a Python binding to the Tk GUI toolkit. It is the standard Python interface for GUIs.',
    fullDescription: 'Build desktop-style applications running in the browser. Tkinter provides standard GUI widgets like buttons, labels, and text boxes, allowing you to create functional graphical user interfaces with Python.',
    tool: 'replit',
    type: 'template',
    category: 'coding',
    tags: ['Graphics', 'Python', 'GUI', 'Tkinter'],
    author: {
      name: 'replit',
      url: 'https://replit.com/@replit',
    },
    installation: {
      type: 'other',
      instructions: 'Click "Use Template" on the Replit project page.',
      url: 'https://replit.com/@replit/tkinter',
    },
    verified: true,
    createdAt: '2025-12-06',
  },
  {
    id: 'replit-game-pygame',
    name: 'Pygame',
    description: 'Pygame is a cross-platform set of Python modules designed for writing video games.',
    fullDescription: 'The go-to library for making games in Python. Handles graphics, sound, and input, letting you focus on game logic. Capable of creating 2D games ranging from simple arcade clones to complex projects.',
    tool: 'replit',
    type: 'template',
    category: 'web',
    tags: ['Games', 'Python', 'Pygame', '2D'],
    author: {
      name: 'replit',
      url: 'https://replit.com/@replit',
    },
    installation: {
      type: 'other',
      instructions: 'Click "Use Template" on the Replit project page.',
      url: 'https://replit.com/@replit/Pygame',
    },
    verified: true,
    createdAt: '2025-12-06',
  },
  {
    id: 'replit-game-kaboom',
    name: 'Kaboom',
    description: 'Kaboom is a Javascript game programming library that helps you make games fast and fun.',
    fullDescription: 'An easy-to-use library for web games. Features a friendly syntax, built-in physics, and input handling. Replit\'s integration often includes asset management for sprites and sounds.',
    tool: 'replit',
    type: 'template',
    category: 'web',
    tags: ['Games', 'JavaScript', 'Kaboom', 'Web'],
    author: {
      name: 'replit',
      url: 'https://replit.com/@replit',
    },
    installation: {
      type: 'other',
      instructions: 'Click "Use Template" on the Replit project page.',
      url: 'https://replit.com/@replit/Kaboom',
    },
    verified: true,
    createdAt: '2025-12-06',
  },
  {
    id: 'replit-game-phaser',
    name: 'Phaser.js Game Starter',
    description: 'Written in phaser.js, use the arrow keys to control the square. Add more to this repl to make it a game!',
    fullDescription: 'A skeleton project for Phaser.js, a powerful framework for HTML5 games. Supports physics, sprites, animations, and more. A great starting point for robust browser games.',
    tool: 'replit',
    type: 'template',
    category: 'web',
    tags: ['Games', 'JavaScript', 'Phaser', 'HTML5'],
    author: {
      name: 'replit',
      url: 'https://replit.com/@replit',
    },
    installation: {
      type: 'other',
      instructions: 'Click "Use Template" on the Replit project page.',
      url: 'https://replit.com/@replit/Phaserjs-Game-Starter',
    },
    verified: true,
    createdAt: '2025-12-06',
  },
  {
    id: 'replit-bot-python-discord',
    name: 'Python Discord Bot',
    description: 'A starting point for build in a Discord bot in Python using the discord.py library.',
    fullDescription: 'The standard template for Discord bots. Includes the discord.py library and basic boilerplate code to connect your bot to the Discord gateway and respond to commands.',
    tool: 'replit',
    type: 'template',
    category: 'coding',
    tags: ['Bots', 'Discord', 'Python', 'Automation'],
    author: {
      name: 'replit',
      url: 'https://replit.com/@replit',
    },
    installation: {
      type: 'other',
      instructions: 'Click "Use Template" on the Replit project page.',
      url: 'https://replit.com/@replit/Python-Discord-Bot',
    },
    verified: true,
    createdAt: '2025-12-06',
  },
  {
    id: 'replit-bot-discordgo',
    name: 'discordgo',
    description: 'A Discord bot template using the Go programming language.',
    fullDescription: 'Build high-performance Discord bots with Go. This template sets up the discordgo library, offering a robust alternative to Python/Node.js for bot development.',
    tool: 'replit',
    type: 'template',
    category: 'coding',
    tags: ['Bots', 'Discord', 'Go', 'Golang'],
    author: {
      name: 'Lord_Poseidon',
      url: 'https://replit.com/@Lord_Poseidon',
    },
    installation: {
      type: 'other',
      instructions: 'Click "Use Template" on the Replit project page.',
      url: 'https://replit.com/@Lord_Poseidon/discordgo',
    },
    verified: true,
    createdAt: '2025-12-06',
  },
  {
    id: 'replit-bot-ai-discord',
    name: 'AI Discord Bot',
    description: 'Generate Stable Diffusion images from a Discord bot using the Prodia API.',
    fullDescription: 'A fun, interactive bot template. Demonstrates how to integrate external APIs (Prodia) into Discord commands. Users can generate images via text prompts directly in chat.',
    tool: 'replit',
    type: 'template',
    category: 'coding',
    tags: ['Bots', 'Discord', 'AI', 'Stable Diffusion'],
    author: {
      name: 'Prodia',
      url: 'https://replit.com/@Prodia',
    },
    installation: {
      type: 'other',
      instructions: 'Click "Use Template" on the Replit project page.',
      url: 'https://replit.com/@Prodia/AI-Discord-Bot',
    },
    verified: true,
    createdAt: '2025-12-06',
  },
  {
    id: 'replit-starter-openai-node',
    name: 'OpenAI Node.js GPT-4',
    description: 'Access the OpenAI GPT-4 chat AI model using Node.js.',
    fullDescription: 'A Javascript/Node.js based starter for GPT-4. Perfect for web developers comfortable with JS who want to build servers or apps powered by OpenAI.',
    tool: 'replit',
    type: 'template',
    category: 'coding',
    tags: ['Starter', 'Node.js', 'OpenAI', 'GPT-4'],
    author: {
      name: 'replit',
      url: 'https://replit.com/@replit',
    },
    installation: {
      type: 'other',
      instructions: 'Click "Use Template" on the Replit project page.',
      url: 'https://replit.com/@replit/OpenAI-Nodejs-GPT-4',
    },
    verified: true,
    createdAt: '2025-12-06',
  }
];
